server:
  port: ${PORT:8094}
  servlet:
    context-path: api/order-history/v1
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_CATALOG_NAME:postgres}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
      generate-ddl: true
